### ISSUE TITLE
Cannot annotate my own gene list with an error

### ISSUE THREAD

**Issue by dahun73** [jcao89757/SCINA#14]
Hello!

I'm a newer using SCINA.

I have one error of running SCINA.
My gene list has only 11 genes. But I can't find any annotated cells...
`scina.results.non <- SCINA(scina.data, list_test, max_iter = 100, 
      convergence_n = 10, 
      convergence_rate = 0.999,
      sensitivity_cutoff = 0.9,
      rm_overlap = FALSE,allow_unknown = FALSE) `
_Error in if (any(keep)) { : missing value where TRUE/FALSE needed_

I searched in Issues section but I think I'm not same situation.
Could you let me know any suggestions about this?

Thanks!

**Comment by jcao89757** [comment]
Hi @dahun73,

Thanks for your interest in our SCINA tool!

Typically your error is caused by the gene list. The error message shows that the algorithm cannot find any genes from the row names of the expression matrix (scina.data) in one or more of your gene signature lists. Would you please check if there is at least one detectable gene in each of your gene list? 

If the problem still exists, would you mind sending me a toy example of your data that replicates the bug? I'll be glad to look into this problem together with you. 

Thanks again for letting me know your problem! Hope this information is helpful!

Best regards, Ze

**Comment by dahun73** [comment]
Hi Ze!

Thank you so much for kind reply :)

I think you are right. When I check the violin plot for those gene list, expression level is quite low and some of genes are not detected.
![image](https://user-images.githubusercontent.com/52641420/122864098-f3774a80-d35e-11eb-9707-9caf2e6e5e61.png)

I think I should change the gene list.... 
Again, thank you so much!!! :) Have a nice day!!

Best,
Dahun

**Comment by jcao89757** [comment]
Hi Dahun,

Glad to hear that your problem has been solved! Please let me know if you have further questions anytime. Wish you all the best for your future work!

Best regards, Ze
