### ISSUE TITLE
Conversion to dense matrix

### ISSUE THREAD

**Issue by jonathangriffiths** [jcao89757/SCINA#6]
Hi there,

This is a really wonderful tool.

Just a little query: on line 68 of the `EM_model.R` file, you are converting the expression matrix into a dense matrix using `exp=as.matrix(exp)`, before you then subset down to the gene markers. For large datasets, this requires a lot of memory! This can regularly lead to an error `Cholmod error 'problem too large'`.

Would it affect performance to either not dens-ify the matrix, or to do so only after subsetting for the marker genes?

Jonny

**Comment by jcao89757** [comment]
Hi Jonny,

Greetings! I'm glad you enjoy using this tool so far!

Yes, you definitely can work this memory problem around by subsetting the `exp` data.frame before converting it to a matrix. Acturally you may subset the `exp` input even before this step, for our tool counts only on those `signature genes`. Please make sure that your `exp` matrix/data.frame after subsetting still has the rows containing the genes existed in your `signature gene` lists, so that the performance of the tool would not be affected.

Hope this information helps to solve your question! Sorry for the very late reply. I'm still a greenhand maintainer. Please let me know if you have any further concerns. Thanks for your interest in our tool!

Best regards, Ze
