### ISSUE TITLE
SCINA error message

### ISSUE THREAD

**Issue by maxlarosa** [jcao89757/SCINA#8]
Hi, I'm working with SCINA but unfortunately when running the SCINA function I obtain the following error message:

Error in if (any(keep)) { : missing value where TRUE/FALSE needed

Can you help me please?

Best

Massimo

**Comment by jcao89757** [comment]
Hi Massimo,

Thanks for raising up your question!

Mostly this error indicates that your signature lists contain many overlapped genes, and after removing overlaps automatically, one or more signature lists may become NULL lists without any genes. Would you like to set the parameter 'rm_overlap=FALSE' and let me know if your question would be solved?

Thanks again for letting me know!

Best regards, Ze

**Comment by maxlarosa** [comment]
Hi Ze, thanks for your response. Yes, I already tried to set  rm_overlap=FALSE
but I obtain the same error.

Best
Massimo

Il mar 21 gen 2020 17:36 Ze Zhang <notifications@github.com> ha scritto:

**Comment by jcao89757** [comment]
Hi Massimo,

Sorry to hear that. Would you please provide me an example of your gene expression matrix and signature lists that can replicate your bug? I'll be glad to take a look and find a solution for you.

Best regards, Ze

**Comment by moldach** [comment]
I'm running into the same issue. When I first stumbled on @maxlarosa issue I thought it was because I had duplicates (I did have duplicates); however, after taking care of this I still get the error:

![weird](https://user-images.githubusercontent.com/5749465/72840064-80e1d700-3c61-11ea-9cb2-093a467f9089.png)

I tried subsetting to find where this issue is occuring. But with some more slicing it looks like it's not row 509 ("LYPLAL1"). Not sure where the error is stemming from here:

![weird02](https://user-images.githubusercontent.com/5749465/72840184-b1297580-3c61-11ea-8351-1af1f17e4bc1.png)

I was going to attach the vector so you can troubleshoot but there seems to be [errors when the length of vector exceeds `n=481`? ](https://twitter.com/MattOldach/status/1219735263737470982)

I will try and [share it saved into a `.csv` instead](https://gofile.io/?c=4jVKLx)

**Comment by maxlarosa** [comment]
Hi Ze, as attachment two datasets

As for GSE72056_melanoma.txt, SCINA works with no issues, setting rm_overlap=FALSE
As for GSE103322_Head_and_neck, SCINA does not work, causing the error: Error in if (any(keep)) { : missing value where TRUE/FALSE needed

The two datasets have normalized expression values as log2(TPM/10+1), where TPM is transcript per million
I verified that both files have not duplicated rows nor NA values.

thanks for your help

Best

Massimo
[GSE103322_Head_and_neck.txt](https://github.com/jcao89757/SCINA/files/4096168/GSE103322_Head_and_neck.txt)
[GSE72056_melanoma.txt](https://github.com/jcao89757/SCINA/files/4096170/GSE72056_melanoma.txt)

**Comment by maxlarosa** [comment]
Here it is the marker list
[marker_genes_immunity_filtered.txt](https://github.com/jcao89757/SCINA/files/4096558/marker_genes_immunity_filtered.txt)

**Comment by jcao89757** [comment]
Hi Massimo and Matthew,

Thank you both for providing the data! I checked on my end and was able to replicate your bug. 

For me, the problem seems like you have too many genes in one signature list. Matthew was right. One step In our algorithm calculates det(A), where A is a n*n diagonal matrix, with n=the number of genes in one list. With a large n, det(A) becomes an enormously huge number that overflows (shown like Inf in R) and crashes the whole algorithm. I can try to bypass that function in the next updated version. 

For now, I would suggest that it's better to reduce the gene numbers in your signature lists. For example, to remove the genes with a low level of variation across all your cells. 20 to 50 genes per signature is good enough to have a good performance with SCINA. 

I will let you know if I find a good way to bypass the det cauculation. Please let me know if this could solve your problem. Thanks again for helping to improve the tool!

Best regards, Ze

**Comment by maxlarosa** [comment]
Thank you Ze, I'll try to reduce the number of genes for signature

Best
Massimo

**Comment by xiebb123456** [comment]
Hi Ze,

I've met the same question 'Error in if (any(keep)) { : missing value where TRUE/FALSE needed'.

When I do trouble shooting, 'prob_mat=t(t(prob_mat)/(1-sum(tao)+colSums(prob_mat)))' cause NAN. Which means the predict dataset do not have specific cell type in marker file, the denominator is 0. 

After add the command 'prob_mat[prob_mat<1e-200] = 1e-200'  extract from 'density_ratio'  method, it works!

Best
Bingbing

**Comment by jcao89757** [comment]
Hi Bingbing,

Thank you for letting us know! Your comment is very helpful. I really have tried to handle the small/large number blowup issues, however, it just could happen everywhere and become unpredictable. I'll keep trying and keep you updated once I find a universal solution.

However, the situation that happened to you is very rare. My concern is that your data quality may not be high enough to make any plausible predictions. For example, the data may contain too many zeros. One possible solution is to include as many signature genes as possible under each cell type. Hope this may help to solve your problem. 

Please let me know if you have any other questions or comments. Thanks a lot for your contribution. Happy holidays!

Best regards, Ze

**Comment by xiebb123456** [comment]
Hi Ze,

You are right, I test 5 and 15 markers in each cell type, both returned very good prediction. So I think few marker (assume they are good marker) is enough to get plausible predictions. 

Thanks for you timely reply and such a great tool!

Bingbing

**Comment by jcao89757** [comment]
It's good to know that acturally certain gene marker subsets works for you! 
Thank you as well, Bingbing! Hope your work goes well and wish you all the best!

Best, Ze
> Hi Ze,
> 
> You are right, I test 5 and 15 markers in each cell type, both returned very good prediction. So I think few marker (assume they are good marker) is enough to get plausible predictions.
> 
> Thanks for you timely reply and such a great tool!
> 
> Bingbing
